import { Routes } from '@angular/router';
import { authGuard } from './shared/auth.guard';
import { adminGuard } from './shared/admin.guard';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./landing/landing-page/landing-page').then((m) => m.LandingPage) },
  { path: 'como-funciona-el-ciclo', loadComponent: () => import('./landing/cycle-guide/cycle-guide').then((m) => m.CycleGuide) },
  { path: 'comparativa', loadComponent: () => import('./landing/comparativa/comparativa').then((m) => m.Comparativa) },
  { path: 'seguridad', loadComponent: () => import('./landing/seguridad/seguridad').then((m) => m.Seguridad) },
  { path: 'terminos', loadComponent: () => import('./landing/terminos/terminos').then((m) => m.Terminos) },
  { path: 'privacidad', loadComponent: () => import('./landing/privacidad/privacidad').then((m) => m.Privacidad) },
  { path: 'iniciar-sesion', loadComponent: () => import('./auth/login/login').then((m) => m.Login) },
  { path: 'crear-cuenta', loadComponent: () => import('./auth/register/register').then((m) => m.Register) },
  { path: 'oauth/callback', loadComponent: () => import('./auth/oauth-callback/oauth-callback').then((m) => m.OauthCallback) },
  { path: 'admin/login', loadComponent: () => import('./admin/admin-login/admin-login').then((m) => m.AdminLogin) },
  {
    path: 'panel',
    canActivate: [authGuard],
    loadComponent: () => import('./panel/panel-layout/panel-layout').then((m) => m.PanelLayout),
    children: [
      { path: '', loadComponent: () => import('./panel/panel-home/panel-home').then((m) => m.PanelHome) },
      { path: 'explorar', loadComponent: () => import('./panel/explore-groups/explore-groups').then((m) => m.ExploreGroups) },
      { path: 'grupos', loadComponent: () => import('./panel/my-groups/my-groups').then((m) => m.MyGroups) },
      { path: 'mayoreo', loadComponent: () => import('./panel/buy-accounts/buy-accounts').then((m) => m.BuyAccounts) },
      { path: 'mayoreo/compras/:id', loadComponent: () => import('./panel/order-payment/order-payment').then((m) => m.OrderPayment) },
      { path: 'mayoreo/:id', loadComponent: () => import('./panel/buy-account-detail/buy-account-detail').then((m) => m.BuyAccountDetail) },
      { path: 'ganancias', loadComponent: () => import('./panel/earnings/earnings').then((m) => m.EarningsPage) },
      { path: 'comisiones', loadComponent: () => import('./panel/commissions/commissions').then((m) => m.CommissionsPage) },
      { path: 'billetera', redirectTo: 'ganancias', pathMatch: 'full' },
      { path: 'perfil', loadComponent: () => import('./panel/profile/profile').then((m) => m.Profile) },
      { path: 'grupos/nuevo', loadComponent: () => import('./panel/create-group/create-group').then((m) => m.CreateGroup) },
      { path: 'grupos/:id/iniciar', loadComponent: () => import('./panel/start-group/start-group').then((m) => m.StartGroup) },
      { path: 'grupos/:id/gestion', loadComponent: () => import('./panel/group-detail/group-detail').then((m) => m.GroupDetail) },
      { path: 'grupos/:id', loadComponent: () => import('./panel/group-detail/group-detail').then((m) => m.GroupDetail) },
      { path: 'grupos/:id/pago', loadComponent: () => import('./panel/group-payment/group-payment').then((m) => m.GroupPayment) },
      { path: 'crear-grupo', redirectTo: 'grupos/nuevo' },
      { path: 'notificaciones', data: { area: 'panel' }, loadComponent: () => import('./shared/notifications-page/notifications-page').then((m) => m.NotificationsPage) },
      { path: 'soporte', loadComponent: () => import('./panel/support-list/support-list').then((m) => m.SupportList) },
      { path: 'soporte/nueva', loadComponent: () => import('./panel/support-new/support-new').then((m) => m.SupportNew) },
      { path: 'soporte/:id', loadComponent: () => import('./panel/support-detail/support-detail').then((m) => m.SupportDetail) },
    ],
  },
  {
    path: 'admin',
    canActivate: [adminGuard],
    loadComponent: () => import('./admin/admin-layout/admin-layout').then((m) => m.AdminLayout),
    children: [
      { path: '', loadComponent: () => import('./admin/admin-dashboard/admin-dashboard').then((m) => m.AdminDashboard) },
      { path: 'proveedores', loadComponent: () => import('./admin/provider-requests/provider-requests').then((m) => m.ProviderRequests) },
      { path: 'mi-tienda/pedidos/:id', loadComponent: () => import('./admin/provider-order-detail/provider-order-detail').then((m) => m.ProviderOrderDetail) },
      { path: 'mi-tienda', loadComponent: () => import('./admin/provider-store/provider-store').then((m) => m.ProviderStore) },
      { path: 'grupos', loadComponent: () => import('./admin/group-requests/group-requests').then((m) => m.GroupRequests) },
      { path: 'grupos/:id', loadComponent: () => import('./admin/group-detail/group-detail').then((m) => m.AdminGroupDetail) },
      { path: 'pagos', loadComponent: () => import('./admin/payments-monitor/payments-monitor').then((m) => m.PaymentsMonitor) },
      { path: 'correos', loadComponent: () => import('./admin/mail-outbox/mail-outbox').then((m) => m.MailOutbox) },
      { path: 'mayoreo-acceso', loadComponent: () => import('./admin/wholesale-access/wholesale-access').then((m) => m.WholesaleAccessAdmin) },
      { path: 'comisiones', loadComponent: () => import('./admin/commissions-queue/commissions-queue').then((m) => m.CommissionsQueue) },
      { path: 'retiros', redirectTo: 'comisiones', pathMatch: 'full' },
      { path: 'incidencias', loadComponent: () => import('./admin/incidents-queue/incidents-queue').then((m) => m.IncidentsQueue) },
      { path: 'incidencias/:id', loadComponent: () => import('./admin/incident-detail/incident-detail').then((m) => m.IncidentDetail) },
      { path: 'notificaciones', data: { area: 'admin' }, loadComponent: () => import('./shared/notifications-page/notifications-page').then((m) => m.NotificationsPage) },
      { path: 'usuarios', loadComponent: () => import('./admin/users-list/users-list').then((m) => m.UsersList) },
    ],
  },
  { path: 'partly-ops-b70ae4/login', redirectTo: 'admin/login', pathMatch: 'full' },
  { path: 'partly-ops-b70ae4', redirectTo: 'admin', pathMatch: 'full' },
  { path: 'partly-ops-b70ae4/incidencias/:id', redirectTo: 'admin/incidencias/:id' },
  { path: 'partly-ops-b70ae4/:section', redirectTo: 'admin/:section' },
];
